- name: Include pre setup task
  ansible.builtin.include_tasks: pre_setup.yaml


- name: Create seed job xml
  ansible.builtin.template:
    src: job_dsl.xml.j2
    dest: /tmp/job_dsl.xml


- name: Create seed Job
  ansible.builtin.shell: |
     java -jar {{ jenkins_cli_folder }}/jenkins-cli.jar  -auth admin:{{ jenkins_admin_password }} -s {{ jenkins_url }} create-job {{ dsl_job_name }} < /tmp/job_dsl.xml


- name: Create dsl workspace workspace direcroty
  ansible.builtin.file:
    path: "{{ jenkins_home_directory }}/workspace/{{ dsl_job_name }}"
    state: directory
    mode: '0750'


- name: Create pipeline job dsl file
  ansible.builtin.template:
    src: Jenkinsfile.j2
    dest: "{{ jenkins_home_directory }}/workspace/{{ dsl_job_name }}/{{ pipeline_job_name }}.jenkinsfile"
  tags: 
    - demo_setup

- name: Build seed job
  ansible.builtin.command:
    argv:
      - java
      - -jar
      - "{{ jenkins_cli_folder }}/jenkins-cli.jar"
      - -auth
      - admin:{{ jenkins_admin_password }}
      - -s
      - "{{ jenkins_url }}" 
      - build 
      - "{{ dsl_job_name }}"

- name: Copy ansible stuff to jenkins pipeline workspace
  ansible.posix.synchronize:
    src: "{{ inventory_dir }}"
    dest: "{{ jenkins_home_directory }}/workspace/{{ pipeline_job_name }}"
    recursive: yes


- name: Build pipeline job
  ansible.builtin.command:
    argv:
      - java
      - -jar
      - "{{ jenkins_cli_folder }}/jenkins-cli.jar"
      - -auth
      - admin:{{ jenkins_admin_password }}
      - -s
      - "{{ jenkins_url }}" 
      - build 
      - "{{ pipeline_job_name }}"

- name: Show Jenkins url
  debug:
    msg: "http://{{ hostvars.jenkins.ansible_ssh_host }}:8080/jenkins"

- name: Show Liferay url
  debug:
    msg: "http://{{ hostvars.liferay.ansible_ssh_host }}:8080/"
